// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servcom.SGA.Infra.Data.Context;

namespace Servcom.SGA.Infra.Data.Migrations
{
    [DbContext(typeof(ServcomSGAContext))]
    [Migration("20190612211336_04_12062019")]
    partial class _04_12062019
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Servcom.SGA.Domain.Atendimentos.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataHoraFim");

                    b.Property<DateTime>("DataHoraInicio");

                    b.Property<DateTime>("DataHoraultimoReingresso");

                    b.Property<string>("HoraCriacao");

                    b.Property<int>("Sequencia");

                    b.Property<int>("Status");

                    b.Property<Guid>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<Guid?>("TipoId")
                        .IsRequired();

                    b.Property<Guid?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasAlternateKey("TipoId", "DataCriacao", "Sequencia");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("Servcom.SGA.Domain.Atendimentos.TipoAtendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao");

                    b.Property<bool>("Prioritario");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("TipoAtendimentos");
                });

            modelBuilder.Entity("Servcom.SGA.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Servcom.SGA.Domain.Atendimentos.Atendimento", b =>
                {
                    b.HasOne("Servcom.SGA.Domain.Atendimentos.TipoAtendimento", "TipoAtendimento")
                        .WithMany("Atendimentos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
